type DesignSystemColors =
| "primary"
| "primary-hover"
| "secondary"
| "black-primary"
| "black-secondary"
| "gray-primary"
| "gray-secondary"
| "white-primary"
| "white-secondary"
| "gray-dark"
| "green-light"
| "green-dark"
